target 'Shahabi' do
	use_frameworks!
	pod 'Firebase'
	pod 'Firebase/Database'
	pod 'Firebase/Core'
	pod 'Firebase/Auth'
	pod 'Firebase/Storage'
	pod 'Alamofire'
	pod 'SDWebImage', '~>3.8'
	pod 'MBProgressHUD', '~> 1.0.0'
end
